name: flutter_alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.8.0+1
  chopper: ^8.0.4
  overlay_support: ^2.1.0
  share_plus: ^10.0.2
  rxdart: ^0.27.1